# Generated by Django 3.2.9 on 2022-01-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='user_by',
            field=models.CharField(max_length=30),
        ),
    ]
