# Generated by Django 3.2.9 on 2022-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist_count',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
