# Generated by Django 3.2.9 on 2021-11-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('create_date', models.DateField(max_length=30)),
                ('listed_by', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField(max_length=30)),
                ('product', models.FloatField(max_length=30)),
                ('create_date', models.DateField(max_length=30)),
                ('user_by', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('user_by', models.CharField(max_length=30)),
                ('date', models.DateField(max_length=30)),
                ('product', models.CharField(max_length=30)),
            ],
        ),
    ]
