# Generated by Django 3.2.9 on 2022-01-11 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bids_user_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
