# Generated by Django 3.2.9 on 2022-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_watchlist_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'listings'},
        ),
        migrations.AlterField(
            model_name='listings',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='listings',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist_count',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
