# Generated by Django 3.2.9 on 2022-01-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='id',
            new_name='uuid',
        ),
    ]
