# Generated by Django 3.2.9 on 2021-12-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctionlistings_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='photo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
