# Generated by Django 3.2.9 on 2022-01-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_id_bids_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='product',
            field=models.IntegerField(max_length=30),
        ),
    ]
