# Generated by Django 3.2.9 on 2021-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
