# Generated by Django 3.2.9 on 2022-01-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
